# Base configs
baseurl: "chrisloewenthal.github.io/photo"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Chris Loewenthal"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
header:
 title: "Photography"
 subtitle: "by Chris Loewenthal"
footer:
 name: "Hey there, my name is Chris"
 bio: "LA based Photographer looking to make the leap professionally."
 github: "test"
web_design: "AJ"

social_urls:
  twitter: "https://www.twitter.com/ram-patra"
  instagram: "https://www.instagram.com/chris_loewenthal"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/chris-loewenthal"
  github: "https://www.github.com/chrisloewenthal"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'